python3 ml-antiunify.py tests/samples/1_dec.in > tests/samples/outputs/anti-unification/1_dec.out
python3 ml-antiunify.py tests/samples/2_conflict.in > tests/samples/outputs/anti-unification/2_conflict.out 
python3 ml-antiunify.py tests/samples/3_oc.in > tests/samples/outputs/anti-unification/3_oc.out
python3 ml-antiunify.py tests/samples/4_double_dec.in > tests/samples/outputs/anti-unification/4_double_dec.in 
python3 ml-antiunify.py tests/samples/5_misc.in > tests/samples/outputs/anti-unification/5_misc.out 
python3 ml-antiunify.py tests/samples/6_same_symbol_dec.in > tests/samples/outputs/anti-unification/6_same_symbol_dec.out 
python3 ml-antiunify.py tests/samples/7_dec_simpl.in > tests/samples/outputs/anti-unification/7_dec_simpl.out 
python3 ml-antiunify.py tests/samples/8_dec_same_depth.in > tests/samples/outputs/anti-unification/8_dec_same_depth.out 
python3 ml-antiunify.py tests/samples/9_dec_rev.in > tests/samples/outputs/anti-unification/9_dec_rev.out 
python3 ml-antiunify.py tests/samples/10_long.in > tests/samples/outputs/anti-unification/10_long.out 
python3 ml-antiunify.py tests/samples/11_multiple_levels.in > tests/samples/outputs/anti-unification/11_multiple_levels.out 
python3 ml-antiunify.py tests/samples/12_paper_cons.in > tests/samples/outputs/anti-unification/12_paper_cons.out 
python3 ml-antiunify.py tests/samples/13_paper_cons_succ.in > tests/samples/outputs/anti-unification/13_paper_cons_succ.out 
python3 ml-antiunify.py tests/samples/14_imp_with_threads_lookup.in > tests/samples/outputs/anti-unification/14_imp_with_threads_lookup.out 
python3 ml-antiunify.py tests/samples/15_imp_with_threads_lookup_io.in > tests/samples/outputs/anti-unification/15_imp_with_threads_lookup_io.out 
python3 ml-antiunify.py tests/samples/16_simple_untyped_lookup.in > tests/samples/outputs/anti-unification/16_simple_untyped_lookup.out 
python3 ml-antiunify.py tests/samples/17_simple_untyped_release_lock.in > tests/samples/outputs/anti-unification/17_simple_untyped_release_lock.out 
python3 ml-antiunify.py tests/samples/18_c_declare_local.in > tests/samples/outputs/anti-unification/18_c_declare_local.out 
python3 ml-antiunify.py tests/samples/19_java_method_invoke.in > tests/samples/outputs/anti-unification/19_java_method_invoke.out 