load tests-setup.maude


*** delete: f(x) = f(x)
rew in PRETTY : pretty(gen-proof1(\app(\symb(100), \evar(1)), \app(\symb(100), \evar(1)))) .
rew in PROOF-GENERATION : check(gen-proof1(\app(\symb(100), \evar(1)), \app(\symb(100), \evar(1)))) .
rew in PRETTY : pretty(gen-proof2(\app(\symb(100), \evar(1)), \app(\symb(100), \evar(1)))) .
rew in PROOF-GENERATION : check(gen-proof1(\app(\symb(100), \evar(1)), \app(\symb(100), \evar(1)))) .

q
