load tests-setup.maude

*** symbol clash: f(a, x) = f(x, b)
rew in PRETTY : pretty(gen-proof1(
\app(\app(\symb(100), \symb(10)), \evar(1)),
\app(\app(\symb(100), \evar(1)), \symb(11))
)) .
rew in PROOF-GENERATION : check(gen-proof1(
\app(\app(\symb(100), \symb(10)), \evar(1)),
\app(\app(\symb(100), \evar(1)), \symb(11))
)) .
rew in PRETTY : pretty(gen-proof2(
\app(\app(\symb(100), \symb(10)), \evar(1)),
\app(\app(\symb(100), \evar(1)), \symb(11))
)) .
rew in PROOF-GENERATION : check(gen-proof2(
\app(\app(\symb(100), \symb(10)), \evar(1)),
\app(\app(\symb(100), \evar(1)), \symb(11))
)) .
q
