load tests-setup.maude

*** orientation: f(y, y) === f(x, g(a))
rew in PRETTY : pretty(gen-proof1(
  \app(\app(\symb(100), \evar(2)), \evar(2)),
  \app(\app(\symb(100), \evar(1)), \app(\symb(101), \symb(10)))
)) .
rew in PROOF-GENERATION : check(gen-proof1(
  \app(\app(\symb(100), \evar(2)), \evar(2)),
  \app(\app(\symb(100), \evar(1)), \app(\symb(101), \symb(10)))
)) .
rew in PRETTY : pretty(gen-proof2(
  \app(\app(\symb(100), \evar(2)), \evar(2)),
  \app(\app(\symb(100), \evar(1)), \app(\symb(101), \symb(10)))
)) .
rew in PROOF-GENERATION : check(gen-proof2(
  \app(\app(\symb(100), \evar(2)), \evar(2)),
  \app(\app(\symb(100), \evar(1)), \app(\symb(101), \symb(10)))
)) .
q