load ../src/proof-generator.maude
*** decomposition
rew in UNIFICATION : < \app(\symb(10), \evar(1)) =? \app(\symb(10), \symb(2)) | .Trace > .

*** orient f(..) = x
rew in UNIFICATION : < \app(\symb(10), \evar(1)) =? \evar(3) | .Trace > .

*** orient a = x
rew in UNIFICATION : < \symb(10) =? \evar(3) | .Trace > .

*** orient + decomposition
rew in UNIFICATION : < \app(\symb(10), \symb(1)) =? \app(\symb(10), \evar(2)) | .Trace > .

*** delete: symb
rew in UNIFICATION : < \symb(1) =? \symb(1) | .Trace > .

*** delete: var
rew in UNIFICATION : < \evar(1) =? \evar(1) | .Trace > .

*** delete vs. decomposition
rew in UNIFICATION : < \app(\symb(10), \symb(1)) =? \app(\symb(10), \symb(1)) | .Trace > .

*** elimination
rew in UNIFICATION : < \evar(1) =? \symb(100), \app(\symb(90), \evar(1)) =? \app(\symb(10), \symb(1)) | .Trace > .

*** elimination + decomposition
rew in UNIFICATION : < \evar(1) =? \symb(100), \app(\symb(10), \evar(1)) =? \app(\symb(10), \symb(1)) | .Trace > .

*** elimination + orientation
rew in UNIFICATION : < \evar(1) =? \symb(100), \evar(1) =? \evar(5) | .Trace > .

*** symbol clash
rew in UNIFICATION : < \app(\symb(10), \evar(1)) =? \app(\symb(11), \symb(2)) | .Trace > .
rew in UNIFICATION : < \app(\symb(10), \evar(1)) =? \symb(11) | .Trace > .
rew in UNIFICATION : < \symb(10) =? \app(\symb(11), \symb(2)) | .Trace > .
rew in UNIFICATION : < \symb(10) =? \symb(11) | .Trace > .

*** symbol clash + decomposition
rew in UNIFICATION : < \app(\symb(10), \symb(1)) =? \app(\symb(10), \symb(2)) | .Trace > .


*** occurs check
rew in UNIFICATION : < \evar(1) =? \app(\symb(2), \evar(1)) | .Trace > .

*** orient + occurs check
rew in UNIFICATION : < \app(\symb(2), \evar(1)) =? \evar(1)  | .Trace > .

*** decomposition + occurs check
rew in UNIFICATION : < \app(\symb(10), \evar(1)) =? \app(\symb(10), \app(\symb(2), \evar(1))) | .Trace > .
q
