load tests-setup.maude

*** delete: f(a) = f(a)
rew in PRETTY : pretty(gen-proof1(\app(\symb(100), \symb(10)), \app(\symb(100), \symb(10)))) .
rew in PROOF-GENERATION : check(gen-proof1(\app(\symb(100), \symb(10)), \app(\symb(100), \symb(10)))) .

rew in PRETTY : pretty(gen-proof2(\app(\symb(100), \symb(10)), \app(\symb(100), \symb(10)))) .
rew in PROOF-GENERATION : check(gen-proof2(\app(\symb(100), \symb(10)), \app(\symb(100), \symb(10)))) .
q
